
variables:
  REGISTRY: sed-team-project:4567
  REG_KAFKA_CONNECT: sed-team-project:4567/sed-dev-group/presistence/kafka-connect
  KAFKA_CONNECT_TAG_THIS_BUILD: $REG_KAFKA_CONNECT:$CI_COMMIT_REF_NAME

stages:
  - build
  - publish
  - deploy

build_kafka_connect:
  image: docker:latest
  stage: build
  script:
    - docker build -t $KAFKA_CONNECT_TAG_THIS_BUILD .
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push $KAFKA_CONNECT_TAG_THIS_BUILD

prod_tag_kafka_connect:
  image: docker:latest
  stage: publish
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY

    - docker pull $KAFKA_CONNECT_TAG_THIS_BUILD
    - docker tag $KAFKA_CONNECT_TAG_THIS_BUILD $REG_KAFKA_CONNECT:latest
    - docker push $REG_KAFKA_CONNECT:latest
  only:
    - master
